# Generated by Django 4.2.11 on 2024-03-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_passwords_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwords',
            name='app_name',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='password',
            field=models.TextField(max_length=10),
        ),
    ]
